name: Build and Deploy to Azure

on:
  push:
    branches:
      - toAzure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Récupérer le code du repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Installer Java 17
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    # 3️⃣ Build Maven project
    - name: Build with Maven
      run: mvn clean package

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app-devops:latest .

    # 5️⃣ Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6️⃣ Push Docker image
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/app-devops:latest

    # 7️⃣ Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-devops-hn 
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: ${{ secrets.DOCKER_USERNAME }}/app-devops:latest
